### ISSUE TITLE
framework not found Metal for architecture armv7

### ISSUE THREAD

**Issue by livingbeams** [vedi/share-bunch-unity3d#1]
Trying run the xcode project generated with the package I get the linker error:
"framework not found Metal for architecture armv7"

Unity3d 4.3.4f1
XCode 5.1.1

**Comment by vedi** [comment]
It's common enough issue. We use linker option -ObjC, and it does not work well in your environment.
Have a look at this article: http://www.appsee.com/blog/dev/xcode-new-link-frameworks-automatically-fix-framework-not-found-metal-for-architecture-armv7
Let me quote from there:

> The Solution
> 
> Until/if Apple addresses this issue, our solution was to disable the “Link Frameworks Automatically” flag when building the framework. This way, the load commands will not be included in the binary and it may be used for non-metal architectures. Nothing else should be affected, since this flag does not seem to work for frameworks referenced by our framework (i.e.: when an app links with Appsee, it would still need to reference the different frameworks which Appsee uses, whether the flag was on or off).

Let me know if you need more help.

**Comment by vedi** [comment]
I'm closing it, let me know if you need additional support.

**Comment by vedi** [comment]
continued at #2
