### ISSUE TITLE
BunchManager and  NativeGateway does not exist in the current context

### ISSUE THREAD

**Issue by skakac** [vedi/share-bunch-unity3d#3]
I receive two errors:

Assets/Plugins/Share/ShareBunch.cs(18,13): error CS0103: The name `BunchManager' does not exist in the current context

Assets/Plugins/Share/ShareBunch.cs(26,9): error CS0103: The name `NativeGateway' does not exist in the current context

**Comment by vedi** [comment]
Please, get sure you installed `native-gateway.unitypackage` before.

**Comment by skakac** [comment]
Yep i saw that right after i posted this issue, sorry.

**Comment by vedi** [comment]
no problem
